### ISSUE TITLE
 I get a warning "export 'default' (imported as 'firebaseui') was not found in 'firebaseui'

### ISSUE THREAD

**Issue by kawamataryo** [isamu/firebase-vue-startup-kit#1]
Hi.
I tried to run this repository. But I get this warning.

```
"export 'default' (imported as 'firebaseui') was not found in 'firebaseui'
```

It seems that you need to fix Firebaseui import in Siginin.vue as below.

```vue
import * as firebaseui from "firebaseui"
```

**Comment by isamu** [comment]
Hi @kawamataryo san,

Thank you for your feedback.
I fixed this issue.

**Comment by Yoel-Ovando** [comment]
Thank you x3

**Comment by jonathanafranio** [comment]
Thank you @kawamataryo
